-- Create Categories Table
create table public.categories (
  id bigint generated by default as identity primary key,
  name text not null,
  icon_name text, -- Store the name of the Lucide icon (e.g., 'Pizza', 'Beef')
  color text,     -- Hex code for background
  icon_color text, -- Hex code for icon
  route text,     -- Navigation route name
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create Food Items Table
create table public.food_items (
  id bigint generated by default as identity primary key,
  name text not null,
  price numeric not null,
  rating numeric default 0,
  image_url text,
  prep_time text default '15-20 min',
  reviews_count int default 0,
  is_popular boolean default false,
  category_id bigint references public.categories(id),
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Insert Sample Categories
insert into public.categories (name, icon_name, color, icon_color, route) values
('Pizza', 'Pizza', '#451a03', '#f97316', 'PizzaPage'),
('Burgers', 'Beef', '#450a0a', '#ef4444', 'BurgerPage'),
('Drinks', 'CupSoda', '#172554', '#3b82f6', 'DrinksPage'),
('Desserts', 'IceCream', '#3b0764', '#a855f7', 'DessertsPage');

-- Insert Sample Food Items
insert into public.food_items (name, price, rating, image_url, is_popular, category_id) values
('Supreme Pizza', 14.99, 4.8, 'https://images.unsplash.com/photo-1513104890138-7c749659a591?w=400', true, 1),
('Wagyu Stack', 18.50, 4.9, 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=400', true, 2);

-- Set up Row Level Security (RLS)
alter table public.categories enable row level security;
alter table public.food_items enable row level security;

-- Allow public read access
create policy "Allow public read access on categories" on public.categories for select using (true);
create policy "Allow public read access on food_items" on public.food_items for select using (true);
